services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: u7ZgMGBvWLsG9JKhxw
      POSTGRES_DB: referall-master
    volumes:
      - ./db/.data:/var/lib/postgresql/data
      - ./db/./config:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"  # Expose DB port for local access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  be:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: referall-be
    ports:
      - "8053:8053"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_JDBCURL: jdbc:postgresql://host.docker.internal:5432/referall-master?autoReconnect=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: u7ZgMGBvWLsG9JKhxw
      JWT_SECRET: "q12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNBq12WE34rT56Yu7I89O0paSDfgHJKlmNB"
      SYMMETRIC_SECRET: "oiuyrnf7584hduseanfi4837dirs945rf8edi85<òzx,9u7t6rerftu54aoiuyrnf7584hduseanfi4837dirs945rf8edi85<òzx,9u7t6rerftu54aoiuyrnf7584hduseanfi4837dirs945rf8edi85<òzx,9u7t6rerftu54aoiuyrnf7584hduseanfi4837dirs945rf8edi85<òzx,9u7t6rerftu54aoiuyrnf7584hduseanfi4837"
      SYMMETRIC_SALT: "1234567890qwerty'13'poiuyt0987654321"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

  fe:
    build:
      context: ./fe
      dockerfile: Dockerfile
      args:
        REACT_APP_BASE_URL: http://localhost:8053
    container_name: referall-fe
    ports:
      - "3000:3000"
    depends_on:
      - be
    restart: unless-stopped
