FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

ARG REACT_APP_BASE_URL=http://localhost:8053
ENV REACT_APP_BASE_URL=$REACT_APP_BASE_URL

EXPOSE 3000
CMD ["npm", "start"]
