spring:
  application:
    name: referall
  devtools:
    restart:
      log-condition-evaluation-delta: false

spring.web.locale: it
server.port: 8080

spring.main.banner-mode: off
spring.servlet.multipart.max-file-size: 4096KB
spring.servlet.multipart.max-request-size: 4096KB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    use-root-path: true
    operationsSorter: alpha
    tagsSorter: alpha
    supported-submit-methods: [ "get", "put", "post", "delete", "options", "head", "patch", "trace" ]
